
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('countries').del()
    .then(function () {
      // Inserts seed entries
      return knex('countries').insert([
        {id: 1, country_name: 'Afghanistan', tld: 'AF', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 2, country_name: 'Albania', tld: 'AL', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 3, country_name: 'Algeria', tld: 'DZ', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 4, country_name: 'Andorra', tld: 'AD', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 5, country_name: 'Angola', tld: 'AO', sadc: 1, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 6, country_name: 'Anguilla', tld: 'AI', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 7, country_name: 'Antigua and Barbuda', tld: 'AG', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 8, country_name: 'Argentina', tld: 'AR', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 9, country_name: 'Armenia', tld: 'AM', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 10, country_name: 'Australia', tld: 'AU', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 11, country_name: 'Austria', tld: 'AT', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 12, country_name: 'Azerbaijan', tld: 'AZ', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 13, country_name: 'Bahamas', tld: 'BS', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 14, country_name: 'Bahrain', tld: 'BH', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 15, country_name: 'Bangladesh', tld: 'BD', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 16, country_name: 'Barbados', tld: 'BB', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 17, country_name: 'Belarus', tld: 'BY', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 18, country_name: 'Belgium', tld: 'BE', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 19, country_name: 'Belize', tld: 'BZ', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 20, country_name: 'Benin', tld: 'BJ', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 21, country_name: 'Bermuda', tld: 'BM', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 22, country_name: 'Bhutan', tld: 'BT', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 23, country_name: 'Bolivia', tld: 'BO', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 24, country_name: 'Bosnia and Herzegovina', tld: 'BA', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 25, country_name: 'Botswana', tld: 'BW', sadc: 1, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 26, country_name: 'Brazil', tld: 'BR', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 27, country_name: 'Brunei', tld: 'BN', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 28, country_name: 'Bulgaria', tld: 'BG', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 29, country_name: 'Burkina Faso', tld: 'BF', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 30, country_name: 'Burundi', tld: 'BI', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 31, country_name: 'Cambodia', tld: 'KH', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 32, country_name: 'Cameroon', tld: 'CM', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 33, country_name: 'Canada', tld: 'CA', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 34, country_name: 'Cape Verde', tld: 'CV', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 35, country_name: 'Cayman Islands', tld: 'KY', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 36, country_name: 'Central African Republic', tld: 'CF', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 37, country_name: 'Chad', tld: 'TD', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 38, country_name: 'Chile', tld: 'CL', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 39, country_name: 'China', tld: 'CN', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 40, country_name: 'Colombia', tld: 'CO', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 41, country_name: 'Comoros', tld: 'KM', sadc: 1, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 42, country_name: 'Congo, Democratic Republic of the', tld: 'CD', sadc: 1, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 43, country_name: 'Congo, Republic of the', tld: 'CG', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 44, country_name: 'Costa Rica', tld: 'CR', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 45, country_name: 'Croatia', tld: 'HR', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 46, country_name: 'Cuba', tld: 'CU', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 47, country_name: 'Cyprus', tld: 'CY', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 48, country_name: 'Czech Republic', tld: 'CZ', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 49, country_name: 'Denmark', tld: 'DK', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 50, country_name: 'Djibouti', tld: 'DJ', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 51, country_name: 'Dominica', tld: 'DM', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 52, country_name: 'Dominican Republic', tld: 'DO', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 53, country_name: 'East Timor', tld: 'TL', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 54, country_name: 'Ecuador', tld: 'EC', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 55, country_name: 'Egypt', tld: 'EG', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 56, country_name: 'El Salvador', tld: 'SV', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 57, country_name: 'Equatorial Guinea', tld: 'GQ', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 58, country_name: 'Eritrea', tld: 'ER', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 59, country_name: 'Estonia', tld: 'EE', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 60, country_name: 'Ethiopia', tld: 'ET', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 61, country_name: 'Faroe Islands', tld: 'FO', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 62, country_name: 'Fiji', tld: 'FJ', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 63, country_name: 'Finland', tld: 'FI', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 64, country_name: 'France', tld: 'FR', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 65, country_name: 'Gabon', tld: 'GA', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 66, country_name: 'Gambia', tld: 'GM', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 67, country_name: 'Georgia', tld: 'GE', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 68, country_name: 'Germany', tld: 'DE', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 69, country_name: 'Ghana', tld: 'GH', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 70, country_name: 'Gibraltar', tld: 'GI', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 71, country_name: 'Greece', tld: 'GR', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 72, country_name: 'Greenland', tld: 'GL', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 73, country_name: 'Grenada', tld: 'GD', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 74, country_name: 'Guatemala', tld: 'GT', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 75, country_name: 'Guernsey', tld: 'GG', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 76, country_name: 'Guinea', tld: 'GN', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 77, country_name: 'Guinea-Bissau', tld: 'GW', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 78, country_name: 'Guyana', tld: 'GY', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 79, country_name: 'Haiti', tld: 'HT', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 80, country_name: 'Honduras', tld: 'HN', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 81, country_name: 'Hong Kong', tld: 'HK', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 82, country_name: 'Hungary', tld: 'HU', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 83, country_name: 'Iceland', tld: 'IS', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 84, country_name: 'India', tld: 'IN', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 85, country_name: 'Indonesia', tld: 'ID', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 86, country_name: 'Iran', tld: 'IR', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 87, country_name: 'Iraq', tld: 'IQ', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 88, country_name: 'Ireland', tld: 'IE', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 89, country_name: 'Isle of Man', tld: 'IM', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 90, country_name: 'Israel', tld: 'IL', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 91, country_name: 'Italy', tld: 'IT', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 92, country_name: 'Ivory Coast', tld: 'CI', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 93, country_name: 'Jamaica', tld: 'JM', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 94, country_name: 'Japan', tld: 'JP', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 95, country_name: 'Jersey', tld: 'JE', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 96, country_name: 'Jordan', tld: 'JO', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 97, country_name: 'Kazakhstan', tld: 'KZ', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 98, country_name: 'Kenya', tld: 'KE', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 99, country_name: 'Kiribati', tld: 'KI', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 100, country_name: 'Korea, Democratic Peoples Republic of (North)', tld: 'KP', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 101, country_name: 'Korea, Republic of (South)', tld: 'KR', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 102, country_name: 'Kosovo', tld: 'XK', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 103, country_name: 'Kuwait', tld: 'KW', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 104, country_name: 'Kyrgyzstan', tld: 'KG', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 105, country_name: 'Laos', tld: 'LA', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 106, country_name: 'Latvia', tld: 'LV', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 107, country_name: 'Lebanon', tld: 'LB', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 108, country_name: 'Lesotho', tld: 'LS', sadc: 1, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 109, country_name: 'Liberia', tld: 'LR', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 110, country_name: 'Libya', tld: 'LY', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 111, country_name: 'Liechtenstein', tld: 'LI', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 112, country_name: 'Lithuania', tld: 'LT', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 113, country_name: 'Luxembourg', tld: 'LU', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 114, country_name: 'Macao', tld: 'MO', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 115, country_name: 'Macedonia', tld: 'MK', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 116, country_name: 'Madagascar', tld: 'MG', sadc: 1, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 117, country_name: 'Malawi', tld: 'MW', sadc: 1, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 118, country_name: 'Malaysia', tld: 'MY', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 119, country_name: 'Maldives', tld: 'MV', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 120, country_name: 'Mali', tld: 'ML', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 121, country_name: 'Malta', tld: 'MT', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 122, country_name: 'Marshall Islands', tld: 'MH', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 123, country_name: 'Mauritania', tld: 'MR', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 124, country_name: 'Mauritius', tld: 'MU', sadc: 1, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 125, country_name: 'Mexico', tld: 'MX', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 126, country_name: 'Micronesia', tld: 'FM', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 127, country_name: 'Moldova', tld: 'MD', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 128, country_name: 'Monaco', tld: 'MC', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 129, country_name: 'Mongolia', tld: 'MN', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 130, country_name: 'Montenegro', tld: 'ME', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 131, country_name: 'Montserrat', tld: 'MS', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 132, country_name: 'Morocco', tld: 'MA', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 133, country_name: 'Mozambique', tld: 'MZ', sadc: 1, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 134, country_name: 'Myanmar', tld: 'MM', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 135, country_name: 'Namibia', tld: 'NA', sadc: 1, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 136, country_name: 'Nauru', tld: 'NR', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 137, country_name: 'Nepal', tld: 'NP', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 138, country_name: 'Netherlands', tld: 'NL', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 139, country_name: 'New Zealand', tld: 'NZ', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 140, country_name: 'Nicaragua', tld: 'NI', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 141, country_name: 'Niger', tld: 'NE', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 142, country_name: 'Nigeria', tld: 'NG', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 143, country_name: 'Norway', tld: 'NO', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 144, country_name: 'Oman', tld: 'OM', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 145, country_name: 'Pakistan', tld: 'PK', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 146, country_name: 'Palau', tld: 'PW', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 147, country_name: 'Palestine', tld: 'PS', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 148, country_name: 'Panama', tld: 'PA', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 149, country_name: 'Papua New Guinea', tld: 'PG', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 150, country_name: 'Paraguay', tld: 'PY', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 151, country_name: 'Peru', tld: 'PE', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 152, country_name: 'Philippines', tld: 'PH', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 153, country_name: 'Pitcairn', tld: 'PN', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 154, country_name: 'Poland', tld: 'PL', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 155, country_name: 'Portugal', tld: 'PT', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 156, country_name: 'Qatar', tld: 'QA', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 157, country_name: 'Romania', tld: 'RO', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 158, country_name: 'Russian Federation', tld: 'RU', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 159, country_name: 'Rwanda', tld: 'RW', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 160, country_name: 'Saint Helena Ascension and Tristan da Cunha', tld: 'SH', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 161, country_name: 'Saint Kitts and Nevis', tld: 'KN', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 162, country_name: 'Saint Lucia', tld: 'LC', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 163, country_name: 'Saint Vincent and the Grenadines', tld: 'VC', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 164, country_name: 'Samoa', tld: 'WS', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 165, country_name: 'San Marino', tld: 'SM', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 166, country_name: 'Sao Tome and Principe', tld: 'ST', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 167, country_name: 'Saudi Arabia', tld: 'SA', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 168, country_name: 'Senegal', tld: 'SN', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 169, country_name: 'Serbia', tld: 'RS', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 170, country_name: 'Seychelles', tld: 'SC', sadc: 1, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 171, country_name: 'Sierra Leone', tld: 'SL', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 172, country_name: 'Singapore', tld: 'SG', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 173, country_name: 'Slovakia', tld: 'SK', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 174, country_name: 'Slovenia', tld: 'SI', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 175, country_name: 'Solomon Islands', tld: 'SB', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 176, country_name: 'Somalia', tld: 'SO', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 177, country_name: 'South Africa', tld: 'ZA', sadc: 1, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 178, country_name: 'South Sudan', tld: 'SS', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 179, country_name: 'Spain', tld: 'ES', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 180, country_name: 'Sri Lanka', tld: 'LK', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 181, country_name: 'Sudan', tld: 'SD', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 182, country_name: 'Suriname', tld: 'SR', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 183, country_name: 'Swaziland', tld: 'SZ', sadc: 1, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 184, country_name: 'Sweden', tld: 'SE', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 185, country_name: 'Switzerland', tld: 'CH', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 186, country_name: 'Syria', tld: 'SY', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 187, country_name: 'Tajikistan', tld: 'TJ', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 188, country_name: 'Tanzania', tld: 'TZ', sadc: 1, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 189, country_name: 'Thailand', tld: 'TH', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 190, country_name: 'Togo', tld: 'TG', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 191, country_name: 'Tonga', tld: 'TO', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 192, country_name: 'Trinidad and Tobago', tld: 'TT', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 193, country_name: 'Tunisia', tld: 'TN', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 194, country_name: 'Turkey', tld: 'TR', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 195, country_name: 'Turkmenistan', tld: 'TM', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 196, country_name: 'Turks and Caicos Islands', tld: 'TC', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 197, country_name: 'Tuvalu', tld: 'TV', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 198, country_name: 'Uganda', tld: 'UG', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 199, country_name: 'Ukraine', tld: 'UA', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 200, country_name: 'United Arab Emirates', tld: 'AE', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 201, country_name: 'United Kingdom', tld: 'GB', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 202, country_name: 'United States', tld: 'US', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 203, country_name: 'Uruguay', tld: 'UY', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 204, country_name: 'Uzbekistan', tld: 'UZ', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 205, country_name: 'Vanuatu', tld: 'VU', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 206, country_name: 'Vatican', tld: 'VA', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 207, country_name: 'Venezuela', tld: 'VE', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 208, country_name: 'Vietnam', tld: 'VN', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 209, country_name: 'Virgin Islands, British', tld: 'VG', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 210, country_name: 'Virgin Islands, US', tld: 'VI', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 211, country_name: 'Yemen', tld: 'YE', sadc: 0, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 212, country_name: 'Zambia', tld: 'ZM', sadc: 1, created_at: new Date(), updated_at: new Date(), deleted_at: null},
        {id: 213, country_name: 'Zimbabwe', tld: 'ZW', sadc: 1, created_at: new Date(), updated_at: new Date(), deleted_at: null},
      ]);
    });
}